rules:
  - patterns: ['src/*/document/*', 'ChangeLog.md', 'readme.md']
    steps: []
  - patterns: ['src/**/test/*', 'src/**/*.Test/*']
    steps: ['build:module', 'test:module']
  - patterns: ['src/.*/.*/help/.*.md', 'src/.*/help/.*.md']
    steps: ['build:module', 'help:module']
  - patterns:
      - src/Accounts/*.csproj
    steps: ['build:all', 'dependence:all', 'test:all']
  - patterns: 
      - src/Accounts/*
    steps: ['build:all', 'breaking-change:module', 'help:module', 'signature:module', 'test:all']
  - patterns:
      - src/*.csproj
    steps: ['build:module', 'dependence:module', 'test:module']
  - patterns: 
      - src/*
    steps: ['build:module', 'breaking-change:module', 'help:module', 'signature:module', 'test:module']
  - patterns: 
      - tools/StaticAnalysis/*
    steps: ['build:all', 'breaking-change:all', 'dependence:all', 'help:all', 'signature:all']
  - patterns:
      - tools/Az.Tools.Predictor/*
    steps: ['sub-task:predictor']
  - patterns:
      - tools/Az.Tools.Installer/*
    steps: ['sub-task:installer']