# Please don't use ADO UI defined scheduled triggers because it takes precedence over YAML scheduled triggers.
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers
name: Docker Release - Az$(Version) $(Date:MMdd) v.$(rev:r)

variables:
  ACR: ''
  ACR_Account: ''
  ACR_Server: ''
  AzVersion: $(Version)
  Latest: false
  Version: 3.3.0

pr: none
trigger: none

pool:
  vmImage: ubuntu-18.04

stages:
- stage: Build
  variables:
    Build_Date: ''
  jobs:
  - job: BuildJob
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $date = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH-mm-ssZ")
          Write-Host "##vso[task.setvariable variable=Build_Date]$date"
        pwsh: true

- stage: Staging
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!
- stage: Publish
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!